<Project>
  <PropertyGroup>
    <OutputPath>$(MSBuildThisFileDirectory)..\..\..\build\lpc-sprite-generator\</OutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\..\..\build\lpc-sprite-generator\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
